# Execute your favorite apps at launch
exec-once = waybar
exec-once = hyprpaper
exec-once = dunst
exec-once = xrdb ~/.Xresources

# Load configuration from Hyprland Settings
exec = ~/.config/nojuza-hyprland-settings/hyprctl.sh
